import type { Metadata } from "next";
import "./globals.css";
import Header from "./ui/Header";

export const metadata: Metadata = {
  title: "KAZKAZI CHAT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="leading-normal tracking-normal antialiased"
      >
        <Header></Header>
        <div className="container w-full mx-auto pt-20 -z-30" style={{ font: "Georgia, sans-serif" }}>
          {children}
        </div>
      </body>
    </html >
  );
}
