FROM ghcr.io/astral-sh/uv:python3.12-alpine

WORKDIR /app
ADD . /app
RUN uv sync --frozen --no-cache

COPY ./app ./app

CMD ["/app/.venv/bin/fastapi", "run", "app/main.py", "--port", "8000", "--host", "0.0.0.0"]
